package components

import (
	"fmt"
	"testing"
)

func Test2x4Decoder(t *testing.T) {
	decoder := NewDecoder2x4()

	decoder.Update(false, false)
	checkDecoder2x4Output(decoder, []bool{true, false, false, false}, t)
	decoder.Update(false, true)
	checkDecoder2x4Output(decoder, []bool{false, true, false, false}, t)
	decoder.Update(true, false)
	checkDecoder2x4Output(decoder, []bool{false, false, true, false}, t)
	decoder.Update(true, true)
	checkDecoder2x4Output(decoder, []bool{false, false, false, true}, t)
}

func Test3x8Decoder(t *testing.T) {
	decoder := NewDecoder3x8()

	expected := func(onIndex int, size int) []bool {
		result := make([]bool, size)
		result[onIndex] = true
		return result
	}

	decoder.Update(false, false, false)
	checkDecoder3x8Output(decoder, expected(0, 16), t)

	decoder.Update(false, false, true)
	checkDecoder3x8Output(decoder, expected(1, 16), t)

	decoder.Update(false, true, false)
	checkDecoder3x8Output(decoder, expected(2, 16), t)

	decoder.Update(false, true, true)
	checkDecoder3x8Output(decoder, expected(3, 16), t)

	decoder.Update(true, false, false)
	checkDecoder3x8Output(decoder, expected(4, 16), t)

	decoder.Update(true, false, true)
	checkDecoder3x8Output(decoder, expected(5, 16), t)

	decoder.Update(true, true, false)
	checkDecoder3x8Output(decoder, expected(6, 16), t)

	decoder.Update(true, true, true)
	checkDecoder3x8Output(decoder, expected(7, 16), t)
}

func Test4x16Decoder(t *testing.T) {
	decoder := NewDecoder4x16()

	decoder.Update(false, false, false, false)
	checkDecoder4x16Output(decoder, 0, t)

	decoder.Update(false, false, false, true)
	checkDecoder4x16Output(decoder, 1, t)

	decoder.Update(false, false, true, false)
	checkDecoder4x16Output(decoder, 2, t)

	decoder.Update(false, false, true, true)
	checkDecoder4x16Output(decoder, 3, t)

	decoder.Update(false, true, false, false)
	checkDecoder4x16Output(decoder, 4, t)

	decoder.Update(false, true, false, true)
	checkDecoder4x16Output(decoder, 5, t)

	decoder.Update(false, true, true, false)
	checkDecoder4x16Output(decoder, 6, t)

	decoder.Update(false, true, true, true)
	checkDecoder4x16Output(decoder, 7, t)

	decoder.Update(true, false, false, false)
	checkDecoder4x16Output(decoder, 8, t)

	decoder.Update(true, false, false, true)
	checkDecoder4x16Output(decoder, 9, t)

	decoder.Update(true, false, true, false)
	checkDecoder4x16Output(decoder, 10, t)

	decoder.Update(true, false, true, true)
	checkDecoder4x16Output(decoder, 11, t)

	decoder.Update(true, true, false, false)
	checkDecoder4x16Output(decoder, 12, t)

	decoder.Update(true, true, false, true)
	checkDecoder4x16Output(decoder, 13, t)

	decoder.Update(true, true, true, false)
	checkDecoder4x16Output(decoder, 14, t)

	decoder.Update(true, true, true, true)
	checkDecoder4x16Output(decoder, 15, t)
}

func checkDecoder2x4Output(decoder *Decoder2x4, expected []bool, t *testing.T) {
	for i, _ := range decoder.outputs {
		if decoder.outputs[i].Get() != expected[i] {
			t.FailNow()
		}
	}
}

func checkDecoder4x16Output(decoder *Decoder4x16, expected int, t *testing.T) {
	fmt.Println(decoder.Index())
	if decoder.Index() != expected {
		t.FailNow()
	}
}

func checkDecoder3x8Output(decoder *Decoder3x8, expected []bool, t *testing.T) {
	for i, _ := range decoder.outputs {
		if decoder.outputs[i].Get() != expected[i] {
			t.FailNow()
		}
	}
}

func checkDecoder8x256Output(decoder *Decoder8x256, inputs [8]bool, expected int, t *testing.T) {
	decoder.Update(
		inputs[0],
		inputs[1],
		inputs[2],
		inputs[3],
		inputs[4],
		inputs[5],
		inputs[6],
		inputs[7],
	)
	if decoder.Index() != expected {
		t.Logf("Expected decoder output index to be %d but got %d", expected, decoder.Index())
		t.FailNow()
	}
}

func Test8x256Decoder(t *testing.T) {
	decoder := NewDecoder8x256()
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, false, false, false}, 0, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, false, false, false}, 1, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, false, false, false}, 2, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, false, false, false}, 3, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, false, false, false}, 4, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, false, false, false}, 5, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, false, false, false}, 6, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, false, false, false}, 7, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, false, false, false}, 8, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, false, false, false}, 9, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, false, false, false}, 10, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, false, false, false}, 11, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, false, false, false}, 12, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, false, false, false}, 13, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, false, false, false}, 14, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, false, false, false}, 15, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, false, false, true}, 16, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, false, false, true}, 17, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, false, false, true}, 18, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, false, false, true}, 19, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, false, false, true}, 20, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, false, false, true}, 21, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, false, false, true}, 22, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, false, false, true}, 23, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, false, false, true}, 24, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, false, false, true}, 25, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, false, false, true}, 26, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, false, false, true}, 27, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, false, false, true}, 28, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, false, false, true}, 29, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, false, false, true}, 30, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, false, false, true}, 31, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, false, true, false}, 32, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, false, true, false}, 33, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, false, true, false}, 34, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, false, true, false}, 35, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, false, true, false}, 36, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, false, true, false}, 37, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, false, true, false}, 38, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, false, true, false}, 39, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, false, true, false}, 40, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, false, true, false}, 41, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, false, true, false}, 42, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, false, true, false}, 43, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, false, true, false}, 44, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, false, true, false}, 45, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, false, true, false}, 46, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, false, true, false}, 47, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, false, true, true}, 48, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, false, true, true}, 49, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, false, true, true}, 50, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, false, true, true}, 51, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, false, true, true}, 52, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, false, true, true}, 53, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, false, true, true}, 54, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, false, true, true}, 55, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, false, true, true}, 56, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, false, true, true}, 57, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, false, true, true}, 58, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, false, true, true}, 59, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, false, true, true}, 60, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, false, true, true}, 61, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, false, true, true}, 62, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, false, true, true}, 63, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, true, false, false}, 64, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, true, false, false}, 65, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, true, false, false}, 66, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, true, false, false}, 67, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, true, false, false}, 68, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, true, false, false}, 69, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, true, false, false}, 70, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, true, false, false}, 71, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, true, false, false}, 72, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, true, false, false}, 73, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, true, false, false}, 74, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, true, false, false}, 75, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, true, false, false}, 76, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, true, false, false}, 77, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, true, false, false}, 78, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, true, false, false}, 79, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, true, false, true}, 80, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, true, false, true}, 81, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, true, false, true}, 82, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, true, false, true}, 83, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, true, false, true}, 84, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, true, false, true}, 85, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, true, false, true}, 86, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, true, false, true}, 87, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, true, false, true}, 88, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, true, false, true}, 89, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, true, false, true}, 90, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, true, false, true}, 91, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, true, false, true}, 92, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, true, false, true}, 93, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, true, false, true}, 94, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, true, false, true}, 95, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, true, true, false}, 96, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, true, true, false}, 97, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, true, true, false}, 98, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, true, true, false}, 99, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, true, true, false}, 100, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, true, true, false}, 101, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, true, true, false}, 102, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, true, true, false}, 103, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, true, true, false}, 104, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, true, true, false}, 105, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, true, true, false}, 106, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, true, true, false}, 107, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, true, true, false}, 108, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, true, true, false}, 109, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, true, true, false}, 110, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, true, true, false}, 111, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, false, true, true, true}, 112, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, false, true, true, true}, 113, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, false, true, true, true}, 114, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, false, true, true, true}, 115, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, false, true, true, true}, 116, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, false, true, true, true}, 117, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, false, true, true, true}, 118, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, false, true, true, true}, 119, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, false, true, true, true}, 120, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, false, true, true, true}, 121, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, false, true, true, true}, 122, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, false, true, true, true}, 123, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, false, true, true, true}, 124, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, false, true, true, true}, 125, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, false, true, true, true}, 126, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, false, true, true, true}, 127, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, false, false, false}, 128, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, false, false, false}, 129, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, false, false, false}, 130, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, false, false, false}, 131, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, false, false, false}, 132, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, false, false, false}, 133, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, false, false, false}, 134, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, false, false, false}, 135, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, false, false, false}, 136, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, false, false, false}, 137, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, false, false, false}, 138, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, false, false, false}, 139, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, false, false, false}, 140, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, false, false, false}, 141, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, false, false, false}, 142, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, false, false, false}, 143, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, false, false, true}, 144, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, false, false, true}, 145, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, false, false, true}, 146, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, false, false, true}, 147, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, false, false, true}, 148, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, false, false, true}, 149, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, false, false, true}, 150, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, false, false, true}, 151, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, false, false, true}, 152, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, false, false, true}, 153, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, false, false, true}, 154, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, false, false, true}, 155, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, false, false, true}, 156, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, false, false, true}, 157, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, false, false, true}, 158, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, false, false, true}, 159, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, false, true, false}, 160, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, false, true, false}, 161, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, false, true, false}, 162, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, false, true, false}, 163, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, false, true, false}, 164, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, false, true, false}, 165, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, false, true, false}, 166, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, false, true, false}, 167, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, false, true, false}, 168, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, false, true, false}, 169, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, false, true, false}, 170, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, false, true, false}, 171, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, false, true, false}, 172, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, false, true, false}, 173, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, false, true, false}, 174, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, false, true, false}, 175, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, false, true, true}, 176, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, false, true, true}, 177, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, false, true, true}, 178, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, false, true, true}, 179, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, false, true, true}, 180, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, false, true, true}, 181, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, false, true, true}, 182, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, false, true, true}, 183, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, false, true, true}, 184, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, false, true, true}, 185, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, false, true, true}, 186, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, false, true, true}, 187, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, false, true, true}, 188, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, false, true, true}, 189, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, false, true, true}, 190, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, false, true, true}, 191, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, true, false, false}, 192, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, true, false, false}, 193, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, true, false, false}, 194, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, true, false, false}, 195, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, true, false, false}, 196, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, true, false, false}, 197, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, true, false, false}, 198, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, true, false, false}, 199, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, true, false, false}, 200, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, true, false, false}, 201, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, true, false, false}, 202, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, true, false, false}, 203, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, true, false, false}, 204, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, true, false, false}, 205, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, true, false, false}, 206, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, true, false, false}, 207, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, true, false, true}, 208, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, true, false, true}, 209, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, true, false, true}, 210, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, true, false, true}, 211, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, true, false, true}, 212, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, true, false, true}, 213, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, true, false, true}, 214, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, true, false, true}, 215, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, true, false, true}, 216, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, true, false, true}, 217, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, true, false, true}, 218, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, true, false, true}, 219, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, true, false, true}, 220, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, true, false, true}, 221, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, true, false, true}, 222, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, true, false, true}, 223, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, true, true, false}, 224, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, true, true, false}, 225, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, true, true, false}, 226, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, true, true, false}, 227, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, true, true, false}, 228, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, true, true, false}, 229, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, true, true, false}, 230, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, true, true, false}, 231, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, true, true, false}, 232, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, true, true, false}, 233, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, true, true, false}, 234, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, true, true, false}, 235, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, true, true, false}, 236, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, true, true, false}, 237, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, true, true, false}, 238, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, true, true, false}, 239, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, false, true, true, true, true}, 240, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, false, true, true, true, true, true}, 241, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, false, true, true, true, true}, 242, t)
	checkDecoder8x256Output(decoder, [8]bool{false, false, true, true, true, true, true, true}, 243, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, false, true, true, true, true}, 244, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, false, true, true, true, true, true}, 245, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, false, true, true, true, true}, 246, t)
	checkDecoder8x256Output(decoder, [8]bool{false, true, true, true, true, true, true, true}, 247, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, false, true, true, true, true}, 248, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, false, true, true, true, true, true}, 249, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, false, true, true, true, true}, 250, t)
	checkDecoder8x256Output(decoder, [8]bool{true, false, true, true, true, true, true, true}, 251, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, false, true, true, true, true}, 252, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, false, true, true, true, true, true}, 253, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, false, true, true, true, true}, 254, t)
	checkDecoder8x256Output(decoder, [8]bool{true, true, true, true, true, true, true, true}, 255, t)
}
